Repository fga-eps-mds/2021.1-Oraculo-FrontEnd, pull requests merged in 2021-11, with the labels that each got.

#42 Limiting SEI number fga-eps-mds/2021.1-Oraculo#138
  src/Components/Process/index.js
Labels: BUG, HOTFIX, EASY

#43 73 tela visualizar processo
  src/Components/DropDownButton/index.js
  src/Components/SectionMovBlock/index.js
  src/Pages/ViewRecord/index.js
  src/Pages/ViewRecord/style.js
  src/Routes.js
  src/Services/Axios/processService.js
  src/Services/Axios/profileService.js
Labels: MDS, MEDIUM

#44 140 datepicker
  package.json
  src/Pages/CreateRecord/index.js
  src/Pages/CreateRecord/styles.js
  yarn.lock
Labels: FEATURE, EASY

#45 139 get sections and departments
  src/Services/Axios/processService.js
  src/Services/Axios/profileService.js
Labels: MDS, FEATURE, EASY

#46 Erase duplicated function fga-eps-mds/2021.1-Oraculo#149
  src/Services/Axios/profileService.js
Labels: BUG, DEVOPS, HOTFIX, EASY

#48 124 alterar nomes
  src/Pages/CreateUser/index.js
  src/Pages/ViewAllFields/index.js
  src/Pages/ViewAllFields/styles.js
Labels: BUG, EASY

#50 145 completar dados do registro
  src/Pages/ViewRecord/index.js
  src/Pages/ViewRecord/style.js
Labels: EPS, MDS, MEDIUM

#51 148 integrar pagina de visualizar todos os registros a de visualizar registro
  src/Components/PocketDocument/index.js
  src/Components/PocketDocument/styles.js
  src/Components/Process/index.js
Labels: EPS, MDS, EASY

#47 116 adicionar registros departamento homepage
  src/Pages/CreateRecord/index.js
  src/Pages/HomePage/index.js
  src/Pages/HomePage/styles.js
  src/Pages/ViewProfile/index.js
  src/Services/Axios/processService.js
Labels: BUG, EPS, MDS, FEATURE, MEDIUM

#53 Fix button fga-eps-mds/2021.1-Oraculo#152
  src/Pages/CreateRecord/index.js
Labels: BUG, EPS, HOTFIX, EASY

#54 Hotfix Botão Voltar em Ver Registro
  src/Pages/ViewRecord/index.js
Labels: EPS, MDS, HOTFIX, EASY

#55 159 listar usuarios
  src/Components/HeaderWithButtons/index.js
  src/Components/PocketUser/index.js
  src/Components/PocketUser/style.js
  src/Pages/ViewAllUsers/index.js
  src/Pages/ViewAllUsers/styles.js
  src/Routes.js
  src/Services/Axios/profileService.js
Labels: EPS, MDS, MEDIUM

#56 155 barra de pesquisa em todos registros
  src/Pages/AllRegistersScreen/index.js
  src/Pages/AllRegistersScreen/styles.js
Labels: FEATURE, EASY

#58 121 cadastro usuario registros
  src/Pages/CreateUser/index.js
  src/Pages/CreateUser/sections.js
  src/Pages/CreateUser/styles.js
  src/Pages/ViewProfile/index.js
  src/Services/Axios/processService.js
Labels: BUG, FEATURE, MEDIUM

#59 144 fix visualizar perfil
  src/Pages/ViewProfile/index.js
Labels: BUG, EPS, MDS, FEATURE

#57 160 editar registro
  src/Pages/CreateProcess/index.js
  src/Pages/EditRecord/index.js
  src/Pages/ViewRecord/index.js
  src/Pages/ViewRecord/style.js
  src/Routes.js
  src/Services/Axios/processService.js
Labels: EPS, MDS, FEATURE, MEDIUM

#60 165 alterar parametros endpoint edituser
  src/Components/HeaderWithButtons/index.js
  src/Pages/CreateUser/index.js
  src/Pages/ViewProfile/index.js
  src/Services/Axios/profileService.js
Labels: EPS, MDS, FEATURE

#61 Update sonar properties file fga-eps-mds/2021.1-Oraculo#168
  sonar-project.properties
Labels: DEVOPS, EPS, ANALYTICS

#63 171 verificar user logado
  src/Pages/LoginScreen/index.js
Labels: BUG, EPS, HOTFIX

#64 fga-eps-mds/2021.1-Oraculo#173 changed value created_by
  src/Pages/CreateRecord/index.js
Labels: MDS, HOTFIX

#65 172 nome secao departamento homepage
  src/Pages/HomePage/index.js
Labels: BUG, EPS, HOTFIX

#67 174 remover numeros magicos
  src/Pages/CreateUser/index.js
Labels: EPS, HOTFIX

#68 175 remover none departamentos
  src/Pages/AllDepartmentsScreen/index.js
Labels: BUG, EPS, HOTFIX

#69 176 remover none secao
  src/Pages/AllSections/index.js
Labels: BUG, EPS, HOTFIX

#70 177 corrigir placeholder
  src/Pages/CreateDepartment/index.js
  src/Pages/CreateSection/index.js
Labels: EPS, HOTFIX, EASY

#71 178 correct header
  src/Components/HeaderWithButtons/index.js
  src/Components/HeaderWithButtons/styles.js
Labels: EPS, EASY

#74 188 mudar paginacao para mais registros
  src/Pages/AllRegistersScreen/index.js
  src/Pages/HomePage/index.js
Labels: EPS, MDS, EASY

#76 Updating screen when forwarding register fga-eps-mds/2021.1-Oraculo#193
  src/Pages/ViewRecord/index.js
Labels: HOTFIX

#77 195 resolver code smells
  src/Components/Departments/index.js
  src/Components/Fields/index.js
  src/Components/HeaderWithButtons/index.js
  src/Components/Pagination/style.js
  src/Components/PocketUser/index.js
  src/Components/Process/index.js
  src/Components/SectionMovBlock/index.js
  src/Components/Sections/index.js
  src/Pages/AllRegistersScreen/index.js
  src/Pages/CreateUser/index.js
  src/Pages/HomePage/index.js
  src/Pages/LoginScreen/index.js
  src/Pages/ViewAllFields/index.js
  src/Pages/ViewAllUsers/index.js
  src/Pages/ViewAllUsers/styles.js
  src/Pages/ViewRecord/index.js
  src/Services/Axios/processService.js
  src/Services/Axios/profileService.js
Labels: EPS, MDS, HOTFIX, MEDIUM

#78 180 verificar token login
  package.json
  src/Pages/LoginScreen/index.js
  src/Services/Axios/profileService.js
Labels: HOTFIX

#82 185 exibir sei existente
  README.md
  package.json
  src/App.test.js
  src/Constants/baseUrls.js
  src/Pages/CreateRecord/index.js
  src/Pages/HomePage/index.js
  src/Services/Axios/processService.js
  yarn.lock
Labels: MDS, FEATURE, MEDIUM

#83 #200 Troca de Favicon e titulo
  public/favicon.ico
  public/index.html
  public/logo-dark-minimal.ico
Labels: MDS, EASY

#84 Update yarn.lock fga-eps-mds/2021.1-Oraculo#202
  yarn.lock
Labels: BUG, DEVOPS, EPS, HOTFIX

#86 197 verify user token
  src/Auth/Auth.js
  src/Routes.js
Labels: BUG, EPS, HOTFIX

#87 204 alertar usuario token expirado
  src/Routes.js
Labels: EPS, FEATURE, MEDIUM

#85 187 edicao de departamentos
  src/Components/Departments/index.js
  src/Components/PocketDepartment/index.js
  src/Pages/EditDepartment/index.js
  src/Routes.js
  src/Services/Axios/profileService.js
Labels: EPS, MDS, FEATURE, MEDIUM

#90 169 buscar usuario pelo email registro
  src/Pages/ViewRecord/index.js
  src/Services/Axios/processService.js
Labels: MDS, MEDIUM

#91 88 concluir processo
  src/Components/ModalDoubleCheck/index.js
  src/Components/ModalDoubleCheck/styles.js
  src/Components/SectionMovBlock/index.js
  src/Pages/ViewRecord/index.js
  src/Services/Axios/processService.js
Labels: MDS, FEATURE

#92 Bug visualização de header para administradores
  src/Services/Axios/profileService.js
Labels: MDS, HOTFIX, EASY

#93 209 datepicker digitado
  src/Pages/CreateRecord/index.js
  src/Pages/EditRecord/index.js
Labels: EPS, HOTFIX, FEATURE

#96 89 reabrir processo
  src/Components/ModalDoubleCheck/index.js
  src/Components/ModalDoubleCheck/styles.js
  src/Components/SectionMovBlock/index.js
  src/Components/SectionMovBlock/styles.js
  src/Pages/ViewRecord/index.js
  src/Services/Axios/processService.js
Labels: MDS, FEATURE, MEDIUM

#99 217 retirar botao adicionar campo
  src/Components/Filters/styles.js
  src/Pages/CreateRecord/index.js
  src/Pages/ViewAllFields/index.js
Labels: MDS, EASY

#100 216 estados dropdown
  src/Constants/federativeUnits.js
  src/Pages/CreateRecord/index.js
  src/Pages/CreateRecord/styles.js
  src/Pages/EditRecord/index.js
Labels: EPS, MDS, FEATURE

#101 219 corrigir palavras
  src/Components/Filters/index.js
  src/Pages/CreateRecord/index.js
Labels: HOTFIX, EASY

#102 220 centralizar nomes do filtro de pesquisa
  src/Components/Filters/styles.js
  src/Pages/EditRecord/index.js
  src/Pages/ViewRecord/index.js
  src/Pages/ViewRecord/style.js
Labels: EPS, MDS, MEDIUM

#104 224 limit register date
  src/Pages/CreateRecord/index.js
  src/Pages/EditRecord/index.js
Labels: EPS, FEATURE, EASY

#105 226 remove logs
  src/Components/DropDownButton/index.js
  src/Pages/AllRegistersScreen/index.js
  src/Pages/CreateUser/index.js
  src/Pages/CreateUser/sections.js
  src/Pages/EditDepartment/index.js
  src/Pages/LoginScreen/index.js
  src/Pages/ViewProfile/index.js
  src/Pages/ViewRecord/index.js
  src/Services/Axios/BaseService/baseService.js
  src/Services/Axios/processService.js
  src/Services/Axios/profileService.js
Labels: EPS, EASY

#106 227 input mask
  src/Pages/ChangePassword/index.js
  src/Pages/ChangePassword/styles.js
Labels: FEATURE

#108 Add view input on login screen fga-eps-mds/2021.1-Oraculo#228
  src/Components/LoginInput/index.js
  src/Components/LoginInput/style.js
Labels: FEATURE

#113 Corrigir erro ao editar registro fga-eps-mds/2021.1-Oraculo#234
  src/Pages/EditRecord/index.js
Labels: MDS, HOTFIX, EASY

#117 236 mudar botao encaminhar registro
  .github/workflows/devel_oraculo-frontend.yml
  .github/workflows/release.yml
  src/Pages/ViewRecord/index.js
  src/Pages/ViewRecord/style.js
Labels: EASY

#118 Bug fixed fga-eps-mds/2021.1-Oraculo#237
  src/Pages/HomePage/index.js
Labels: HOTFIX, EASY
