Repository fga-eps-mds/2021.1-Oraculo-FrontEnd, pull requests merged in 2021-10, with the labels that each got.

#14 73 tela visualizar processo
  .env
  src/Components/DropDownButton/DivSelectSetor.js
  src/Components/DropDownButton/index.js
  src/Components/FowardSetor/index.js
  src/Components/SectionMovBlock/index.js
  src/Pages/ViewProcess/index.js
  src/Pages/ViewProcess/style.js
Labels: MDS, FEATURE

#24 fga-eps-mds/2021.1-Oraculo#73 fix microservice data acquisition
  src/Pages/ViewRecord/index.js
Labels: MDS

#39 78 us28 editar usuario integracao
  src/Pages/ViewProfile/index.js
  src/Pages/ViewProfile/styles.js
  src/Services/Axios/profileService.js
Labels: MDS, FEATURE

#40 137 fix naming errors
  src/Pages/CreateUser/sections.js
  src/Pages/ViewProfile/index.js
Labels: MDS, HOTFIX, EASY
