Repository fga-eps-mds/2021.1-Oraculo-FrontEnd, pull requests merged in 2021-09, with the labels that each got.

#4 #60 Configurar envio automático do arquivo do sonarcloud
  .github/workflows/release.yml
Labels: DEVOPS, EPS, DOCS

#7 #30 Adicionando rota para página "criar-processo"
  src/Pages/LoginScreen/index.js
  src/Routes.js
Labels: MDS, US

#5 #31 Tela de criação e edição de processo
  docker-compose.yml
  src/Pages/AdminScreen/index.js
  src/Pages/CreateProcess/index.js
  src/Pages/CreateProcess/styles.js
  src/Pages/LoginScreen/index.js
  src/Routes.js
  yarn.lock
Labels: MDS, FEATURE, MEDIUM, US

#9 #84 Cobertura de código funcional no sonar cloud
  .github/workflows/release.yml
  .github/workflows/sonarcloud.yml
  package.json
  sonar-project.properties
  src/App.test.js
  test-report.xml
Labels: DEVOPS, EPS
